name: Update Blog Posts

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version

      - name: Install dependencies
        run: |
          npm install rss-parser
          npm install date-fns

      - name: Run update script
        run: node updateReadme.js

      - name: Commit and Push changes
        run: |
          git config --global user.name 'jsbard'
          git config --global user.email 'andrew.hickman.dev@gmail.com'
          git add README.md
          git commit -m "Update latest blog posts" -a || exit 0
          git push
